### ISSUE TITLE
What happens to operationMode when targetTemperature is set?

### ISSUE THREAD

**Issue by piejanssens** [dfrommi/openhab-tado#2]
Usually (my) Tado° will be set to automatic or SCHEDULE. When you set the targetTemperature through this binding, will it switch to MANUAL or UNTIL_CHANGE or?

If I understand the README correctly (for my heating only - gen 1 Tado°) I should send for example targetTemperature '21' and operationMode 'UNTIL_CHANGE' within 5 seconds, the binding will combine it and send it as one request to the tado api?

**Comment by dfrommi** [comment]
What happens depends on the current operation mode of your zone.

*Case 1: your zone has an active override, for example UNTIL_CHANGE*
If you only set the target temperature via openhab, then the zone remains in UNTIL_CHANGE mode.

*Case 2: your zone is in SCHEDULE mode*
A temperature change would use the operation mode that you have configured in the tado° mobile or webapp (settings -> select zone -> manual control on tado° device). That's the same operation mode that is also used when you change the temperature directly on the device

I think you slightly misunderstood the 5-seconds section. I should probably rephrase it in the README.
You don't have to or should change more items from the UI, but if you do, then they will be collected.

Let's say you've configured a default operation mode of "UNTIL_CHANGE" in the tado° app, but you rather want a timer, then you can set timer duration and temperature in one go, without intermediate "UNTIL_CHANGE" override.
It's really more a technical detail.

But it's perfectly fine to change only target temperature. It just means that more parameters will be filled automatically.

**Comment by piejanssens** [comment]
Thanks! You should probably add this to the readme 😄
