### ISSUE TITLE
Possibility to override presense ?

### ISSUE THREAD

**Issue by tgeens** [dfrommi/openhab-tado#8]
Would it be possible somehow to register/add a virtual presence device from OpenHAB with Tado, so I could "force" the home-state ?

Use case: override when the babysitter stays home with the kids.

**Comment by dfrommi** [comment]
Interesting use case.
The tado API does currently not offer a way to enforce HOME mode, so a pseudo mobile device would in fact be the only option. 
However, I don't like the idea of creating mobile devices from the binding. It should only operate on existing things, read their state and perform operational tasks on them. I even wouldn't like to alter configuration values from the binding.

But there are 2 ways to achieve what you want to do, but outside of OpenHAB.

1. You might have a tablet at home that's staying at home while the babysitter is there. Then you could install the tado app on the tablet. By default, tado geotracking is disabled on tablets, but you can enable it in the tado app settings. Just do that when the babysitter arrives and disable it afterwards. Then your home is in HOME mode.
2. It might be sufficient to only heat up the living room and the kid's bedroom during that time. Then you can modifiy the relevant blocks in the smart schedule and disable gelocation-based control per block. It's in the block's advanced setting.

Hope that helps.
I will keep your use case in mind and implement the functionality as soon as tado provides an official way to force HOME mode.
